services:
  database:
    image: neo4j:latest
    container_name: loma_neo4j
    ports:
      - '7474:7474' # Hallintaliittymä
      - '7687:7687' # Bolt-yhteys
    environment:
      - NEO4J_AUTH=neo4j/salasana123
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
